services:
    app.context_service:
        class: AppBundle\Service\ContextService
        arguments: ["@service_container"]
    app.statistics_service:
        class: AppBundle\Service\StatisticsService
        arguments: ["@service_container"]
    app.database_connection_service:
        class: AppBundle\Service\DatabaseConnectionService
        arguments: ["@service_container"]
    app.parser.cxt_parser:
        class: AppBundle\Parser\CxtParser
        arguments: ["@service_container"]
    app.parser.csv_parser:
        class: AppBundle\Parser\CsvParser
        arguments: ["@service_container"]
